name: calculator_neumorphism_ui_lego
description: "A Flutter Lego package to use and make beautiful Neumorphism design based calculator."
#publish_to: 'none'
repository: https://github.com/flutter-lego/calculator_neumorphism_ui_lego

version: 1.0.2

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  june_flow_util: #@add
  styled_widget: #@add
  modal_bottom_sheet: #@add
  gap: #@add
  flutter_svg: #@add

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:
  assets:
    - assets/lego/calculator_neumorphism_ui_lego/
  uses-material-design: true

topics:
  - lego